#include "gt_stdioexecutioneventencoder.h"
#include "gt_object.h"
#include "gt_objectmemento.h"
#include <QIODevice>
#include <QJsonDocument>
#include <utility>
std::mutex GtStdioExecutionEventEncoder::s_outputMutex;
namespace { constexpr char prefix[]="@gtlab-operation-v1 "; QJsonObject common(QString const& kind,GtExecutionId const& id){return {{QStringLiteral("version"),1},{QStringLiteral("kind"),kind},{QStringLiteral("executionId"),id.toString()}};} }
GtStdioExecutionEventEncoder::GtStdioExecutionEventEncoder(GtExecutionId id,QIODevice& out,QObject* parent):QObject(parent),m_executionId(std::move(id)),m_output(out){} bool GtStdioExecutionEventEncoder::isTerminal() const noexcept{std::lock_guard<std::mutex> lock(m_mutex);return m_terminal;} void GtStdioExecutionEventEncoder::encodeEvent(GtExecutionEvent e){QJsonObject r=common(QStringLiteral("event"),e.executionId());r.insert(QStringLiteral("sequence"),static_cast<qint64>(e.sequence()));r.insert(QStringLiteral("eventType"),e.eventType());if(e.payloadEncoding()==GtExecutionEvent::PayloadEncoding::Json){r.insert(QStringLiteral("payloadEncoding"),QStringLiteral("json"));r.insert(QStringLiteral("payload"),e.jsonPayload());}else{r.insert(QStringLiteral("payloadEncoding"),QStringLiteral("memento-xml-base64"));r.insert(QStringLiteral("payload"),QString::fromLatin1(e.mementoXml().toBase64()));}writeRecord(std::move(r),false);} bool GtStdioExecutionEventEncoder::encodeResult(GtObject const* result){QJsonObject r=common(QStringLiteral("result"),m_executionId);if(!result){r.insert(QStringLiteral("resultEncoding"),QStringLiteral("null"));r.insert(QStringLiteral("result"),QJsonValue::Null);}else{r.insert(QStringLiteral("resultEncoding"),QStringLiteral("memento-xml-base64"));r.insert(QStringLiteral("result"),QString::fromLatin1(result->toMemento().toByteArray().toBase64()));}return writeRecord(std::move(r),true);} bool GtStdioExecutionEventEncoder::encodeFailure(QString code,QString message,std::optional<QJsonValue> details){if(code.isEmpty()||message.isEmpty())return false;QJsonObject r=common(QStringLiteral("failure"),m_executionId);r.insert(QStringLiteral("errorCode"),std::move(code));r.insert(QStringLiteral("message"),std::move(message));if(details)r.insert(QStringLiteral("details"),*details);return writeRecord(std::move(r),true);} bool GtStdioExecutionEventEncoder::writeRecord(QJsonObject r,bool terminal){std::lock_guard<std::mutex> lock(m_mutex);if(m_terminal||(!terminal&&r.value(QStringLiteral("executionId"))!=m_executionId.toString()))return false;QByteArray line(prefix);line+=QJsonDocument(r).toJson(QJsonDocument::Compact);line+='\n';std::lock_guard<std::mutex> outLock(s_outputMutex);if(m_output.write(line)!=line.size())return false;if(terminal)m_terminal=true;return true;}

