name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build_and_test:
    name: "Build and test"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-2019] # we build on GitHub-provided Windows and Linux images
    runs-on: ${{ matrix.os }} # use value from the matrix
    
    steps:    
    - name: Install dependencies (linux)
      run: sudo apt install ninja-build
      if: matrix.os == 'ubuntu-latest' # conditional, runs this step only on the Ubuntu runner
    - name: Install Ninja (windows)    # Ninja is not available in GitHub-provided images,
                                       # see https://github.com/actions/runner-images/issues/514
      run: choco install ninja         # So let's install it through Chocolatey
      if: matrix.os == 'windows-latest'
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.15.2'
    - uses: ilammy/msvc-dev-cmd@v1 # This action essentially calls vcvarsall.bat for the latest VS in the runner for x64
    - uses: actions/checkout@v3    # Actually check out the sources. GH Actions can run for events that may not require
                                   # sources (e.g. when someone comments on an issue)
    - name: Install dependencies (windows)
      if: startsWith(matrix.os, 'windows')
      shell: powershell
      run: |
        $ProgressPreference = 'SilentlyContinue'
        Invoke-WebRequest -Uri https://gtlab.de/builddeps/hdf5-1.12.1-win64.zip -OutFile hdf5-1.12.1-win64.zip
        Expand-Archive -Path 'hdf5-1.12.1-win64.zip' -DestinationPath "$env:GITHUB_WORKSPACE/build_deps"
        "HDF5_DIR=$env:GITHUB_WORKSPACE\build_deps\hdf5-1.12.1-win64\share\cmake\hdf5" | Out-File -FilePath $env:GITHUB_ENV -Append      
 
    # Here we call CMake manually, there are solutions for that in the Marketplace: https://github.com/marketplace/actions/run-cmake
    - name: Build
      # We don't need to set up the environment variable for CMake to see Qt because the install-qt-action
      # sets up the necessary variables automatically
      run: | 
        dir D:\a\gtlab-core\gtlab-core\build_deps\hdf5-1.12.1-win64
        dir D:\a\gtlab-core\gtlab-core\build_deps\hdf5-1.12.1-win64\share\cmake\hdf5
        dir D:\a\gtlab-core\gtlab-core\build_deps\hdf5-1.12.1-win64\lib
        cmake -S . -B build -G "Ninja Multi-Config" -DHDF5_DIR=D:\a\gtlab-core\gtlab-core\build_deps\hdf5-1.12.1-win64\share\cmake\hdf5 --debug-find && cmake --build build --config Debug


  documentation:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt install -y doxygen
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt
    - name: Run doxygen
      run: |
        cd docs
        doxygen
    - name: Create documentation
      run: |
        cd docs
        sphinx-build . html
    - name: Save as artifact
      uses: actions/upload-artifact@v4
      with:
        name: doc-devel
        path: |
          docs/html
